DROP TABLE IF EXISTS `animal`;

CREATE TABLE `animal` (
	`id` BIGINT AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL,
	`genus` VARCHAR(255) NOT NULL,
    `dietary_group` VARCHAR(255) NOT NULL,
	`age` INT NOT NULL,
	PRIMARY KEY(`id`)
);